In [2]:
# workflow of ML --->
# Data Ingestion --> Data cleaning and preprocessing --> select Ml Model 
# --->  Model Training --> Model Prediction ---> calculate performance metrics

In [3]:
# #  Data cleaning and preprocessing --->
# # Data -> x_train, x_test, y_train, y_test
# # Machine(x_train, y_train) 
# 1+1 = 2
# 2+2 = 4
# 3+2 = 5

# Machine (5+7) ----??? ---> prdict 13

# 5+7 = 12
# 12 = x_test
# 13 = y_test
# Machine (y_pred, y_test) ---> performance metrics (accuracy, precision, recall, f1-score)

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\covid_toy - covid_toy.csv')

In [6]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [9]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [10]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [11]:
x

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [12]:
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: str

In [15]:
x.shape ## input or dependent data

(100, 5)

In [ ]:
y.shape # target data  or indepent data

(100,)

In [18]:
from sklearn.model_selection import train_test_split, train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [19]:
x_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [20]:
x_test

    age  gender       fever   cough       city
83   17  Female  104.000000    Mild    Kolkata
53   83    Male   98.000000    Mild      Delhi
70   68  Female  101.000000  Strong      Delhi
45   72    Male   99.000000    Mild  Bangalore
44   20    Male  102.000000  Strong      Delhi
39   50  Female  103.000000    Mild    Kolkata
22   71  Female   98.000000  Strong    Kolkata
80   14  Female   99.000000    Mild     Mumbai
10   75  Female  100.844444    Mild      Delhi
0    60    Male  103.000000    Mild    Kolkata
18   64  Female   98.000000    Mild  Bangalore
30   15    Male  101.000000    Mild      Delhi
73   34    Male   98.000000  Strong    Kolkata
33   26  Female   98.000000    Mild    Kolkata
90   59  Female   99.000000  Strong      Delhi
4    65  Female  101.000000    Mild     Mumbai
76   80    Male  100.000000    Mild  Bangalore
77    8  Female  101.000000    Mild    Kolkata
12   25  Female   99.000000  Strong    Kolkata
31   83    Male  103.000000    Mild    Kolkata

In [22]:
y_train

55    Yes
88     No
26    Yes
42    Yes
69     No
     ...
60    Yes
71     No
14     No
92     No
51    Yes
Name: has_covid, Length: 80, dtype: str

In [23]:
y_test

83     No
53    Yes
70     No
45     No
44     No
39     No
22    Yes
80    Yes
10     No
0      No
18    Yes
30    Yes
73    Yes
33     No
90     No
4      No
76    Yes
77     No
12     No
31     No
Name: has_covid, dtype: str

In [24]:
print("Total data shape:" ,df.shape)
print("------------------------------------>")
print("Input data shape:" ,x.shape)
print("x_train shape:" ,x_train.shape)
print("x_test shape:" ,x_test.shape)
print("------------------------------------>")
print("Target data shape:" ,y.shape)
print("y_train shape:" ,y_train.shape)
print("y_test shape:" ,y_test.shape)

Total data shape: (100, 6)
------------------------------------>
Input data shape: (100, 5)
x_train shape: (80, 5)
x_test shape: (20, 5)
------------------------------------>
Target data shape: (100,)
y_train shape: (80,)
y_test shape: (20,)