In [3]:
#  Encoding
#     ---- > Transform your categorical data into Numerical data .
# (1). Label ----- > It will encode data 1-1 columns .
# (2). Ordinal--- > It will encode data more than 1 columns .
# (3). OneHot ---- > It will create new column based on sub-categories but it has only values not column name.
# (4). get_dummies --- > It will create new column based on sub-categories but it shows column name with values

# Label Encoder

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\toyota - toyota.csv')

In [6]:
df.head(3)

  model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0  GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1  GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0
2  GT86  2015  13998       Manual    27469   Petrol  265  36.2         2.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6738 entries, 0 to 6737
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         6738 non-null   str
 1   year          6738 non-null   int64
 2   price         6738 non-null   int64
 3   transmission  6738 non-null   str
 4   mileage       6738 non-null   int64
 5   fuelType      6738 non-null   str
 6   tax           6738 non-null   int64
 7   mpg           6738 non-null   float64
 8   engineSize    6738 non-null   float64
dtypes: float64(2), int64(4), str(3)
memory usage: 473.9 KB

In [8]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [9]:
x = df.drop(columns = ['price'])
y = df['price']

In [10]:
x['model'] = lb.fit_transform(x['model'])
x['transmission'] = lb.fit_transform(x['transmission'])
x['fuelType'] = lb.fit_transform(x['fuelType'])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [13]:
x_train_sc = sc.fit_transform(x_train)

In [14]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [15]:
np.round(x_train_new.describe(),2)

,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
count,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00
mean,0.00,-0.00,0.00,0.00,0.00,-0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.17,-8.58,-1.03,-1.19,-1.99,-1.28,-3.74,-3.36
25%,-0.88,-0.34,-1.03,-0.70,-1.07,-1.28,-0.48,-1.07
50%,-0.45,0.12,0.49,-0.23,0.77,0.55,-0.02,0.07
75%,1.28,0.57,0.49,0.43,0.77,0.68,0.36,0.76
max,1.28,1.49,3.54,7.94,0.77,6.36,10.64,6.94

# Ordinal Encoder

In [16]:
df = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\covid_toy - covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [17]:
df.groupby('cough').size()

cough
Mild      62
Strong    38
dtype: int64

In [18]:
df = df.drop(columns = ['age','fever'])

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[
    ['Male', 'Female'],
    ['Mild', 'Strong'],
    ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
    ['Yes', 'No']
])

In [21]:
new_df = oe.fit_transform(df)

In [22]:
new_df

array([[0., 0., 0., 1.],
       [0., 0., 2., 0.],
       [0., 0., 2., 1.],
       [1., 0., 0., 1.],
       [1., 0., 3., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 1.],
       [1., 1., 3., 0.],
       [1., 1., 1., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 3., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 2., 1.],
       [1., 0., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 1.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 2., 0.],
       [1., 1., 0., 1.],
       [0., 0., 3., 1.],
       [1., 0., 0., 0.],
       [1., 1., 2., 1.],
       [0., 0., 0., 1.],
       [1., 1., 3., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 1.],
       [1., 1., 2., 0.],
       [1., 0., 0., 1.],
       [0., 0., 3., 0.],
       [1., 1., 1., 1.],
       [1., 0., 1., 1.],
       [0., 0., 0., 1.],
       [1., 0., 2., 0.],
       [1., 0., 0., 1.],
       [1., 0., 2., 1.],
       [0., 0., 0., 0.],
       [0., 0., 2., 0.],
       [1., 0., 1., 0.],
       [0., 1., 2., 1.],
       [0., 0., 1., 1.],
       [1., 0., 3., 1.],
       [1., 0., 1., 1.],
       [0., 1., 1., 1.],
       [0., 0., 3., 1.],
       [0., 0., 2., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [0., 0., 2., 0.],
       [1., 0., 3., 0.],
       [1., 0., 3., 0.],
       [0., 1., 0., 1.],
       [1., 1., 1., 1.],
       [0., 1., 3., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 3., 1.],
       [1., 1., 1., 0.],
       [0., 0., 1., 1.],
       [0., 0., 3., 1.],
       [1., 0., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 0., 2., 1.],
       [1., 1., 2., 1.],
       [1., 1., 2., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 2., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 3., 0.],
       [0., 0., 2., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 1., 3., 1.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 1., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 1.],
       [1., 1., 2., 1.],
       [0., 0., 2., 0.],
       [1., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 1.],
       [1., 1., 0., 0.],
       [1., 0., 1., 1.],
       [1., 1., 3., 1.],
       [1., 1., 0., 0.]])

In [23]:
new_df = oe.fit_transform(df)

new_df = pd.DataFrame(new_df, columns=df.columns)

print(new_df.head())

   gender  cough  city  has_covid
0     0.0    0.0   0.0        1.0
1     0.0    0.0   2.0        0.0
2     0.0    0.0   2.0        1.0
3     1.0    0.0   0.0        1.0
4     1.0    0.0   3.0        1.0

#  one hot encoding

In [24]:
# OneHot Encoding

# column has_covid['y', 'n'] --- > new column y_has_covid , n_has_covid -- >
#  but contaisn only values not column name.

In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv(r'C:\Users\PIYUSH\OneDrive\Desktop\Data-Science\Datasets\covid_toy - covid_toy.csv')

In [27]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [28]:
df = df.drop(columns = ['age','fever'])

In [29]:
df.head(3)

  gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes
2   Male  Mild    Delhi        No

In [30]:
# drop='first' → Har category group ki pehli category hata deta hai, taaki duplicate information na rahe.
# sparse_output=False → Output normal NumPy array mein deta hai, sparse matrix nahi.
# dtype=np.float32 → Output values ka data type float32 rakhta hai (kam memory use hoti hai).

In [31]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.float32)

In [34]:
# gender --->2 --->1
# city --->4 ----->3
# has_covid --->2 --->1
# cought --->2 --->1

In [35]:
ohe.fit_transform(df[['gender','cough','city','has_covid']])

array([[1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [1., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.]], dtype=float32)

# Get Dummies

In [37]:
a = pd.get_dummies(df,columns = ['gender','city','cough','has_covid'])

In [38]:
a = a.astype('int')

In [39]:
a

,gender_Female,gender_Male,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai,cough_Mild,cough_Strong,has_covid_No,has_covid_Yes
0,0,1,0,0,1,0,1,0,1,0
1,0,1,0,1,0,0,1,0,0,1
2,0,1,0,1,0,0,1,0,1,0
3,1,0,0,0,1,0,1,0,1,0
4,1,0,0,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
95,1,0,1,0,0,0,1,0,1,0
96,1,0,0,0,1,0,0,1,0,1
97,1,0,1,0,0,0,1,0,1,0
98,1,0,0,0,0,1,0,1,1,0
99,1,0,0,0,1,0,0,1,0,1