In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [10]:
df = sns.load_dataset('titanic')

In [20]:
df

     survived  pclass     sex        age  ...  deck  embark_town  alive  alone
0           0       3    male  22.000000  ...   NaN  Southampton     no  False
1           1       1  female  38.000000  ...     C    Cherbourg    yes  False
2           1       3  female  26.000000  ...   NaN  Southampton    yes   True
3           1       1  female  35.000000  ...     C  Southampton    yes  False
4           0       3    male  35.000000  ...   NaN  Southampton     no   True
..        ...     ...     ...        ...  ...   ...          ...    ...    ...
886         0       2    male  27.000000  ...   NaN  Southampton     no   True
887         1       1  female  19.000000  ...     B  Southampton    yes   True
888         0       3  female  29.699118  ...   NaN  Southampton     no  False
889         1       1    male  26.000000  ...     C    Cherbourg    yes   True
890         0       3    male  32.000000  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]

In [12]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 100.4 KB

In [14]:
df['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [15]:
df['age'] = df['age'].fillna(df['age'].mean())

In [16]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [22]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [24]:
df.drop(['deck','adult_male','embark_town','alive','who','class'],axis=1,inplace=True)

In [25]:
df

     survived  pclass     sex        age  sibsp  parch     fare embarked  alone
0           0       3    male  22.000000      1      0   7.2500        S  False
1           1       1  female  38.000000      1      0  71.2833        C  False
2           1       3  female  26.000000      0      0   7.9250        S   True
3           1       1  female  35.000000      1      0  53.1000        S  False
4           0       3    male  35.000000      0      0   8.0500        S   True
..        ...     ...     ...        ...    ...    ...      ...      ...    ...
886         0       2    male  27.000000      0      0  13.0000        S   True
887         1       1  female  19.000000      0      0  30.0000        S   True
888         0       3  female  29.699118      1      2  23.4500        S  False
889         1       1    male  26.000000      0      0  30.0000        C   True
890         0       3    male  32.000000      0      0   7.7500        Q   True

[891 rows x 9 columns]

In [26]:
df = df.dropna()

In [27]:
df

     survived  pclass     sex        age  sibsp  parch     fare embarked  alone
0           0       3    male  22.000000      1      0   7.2500        S  False
1           1       1  female  38.000000      1      0  71.2833        C  False
2           1       3  female  26.000000      0      0   7.9250        S   True
3           1       1  female  35.000000      1      0  53.1000        S  False
4           0       3    male  35.000000      0      0   8.0500        S   True
..        ...     ...     ...        ...    ...    ...      ...      ...    ...
886         0       2    male  27.000000      0      0  13.0000        S   True
887         1       1  female  19.000000      0      0  30.0000        S   True
888         0       3  female  29.699118      1      2  23.4500        S  False
889         1       1    male  26.000000      0      0  30.0000        C   True
890         0       3    male  32.000000      0      0   7.7500        Q   True

[889 rows x 9 columns]

In [28]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
alone       0
dtype: int64

In [29]:
df

     survived  pclass     sex        age  sibsp  parch     fare embarked  alone
0           0       3    male  22.000000      1      0   7.2500        S  False
1           1       1  female  38.000000      1      0  71.2833        C  False
2           1       3  female  26.000000      0      0   7.9250        S   True
3           1       1  female  35.000000      1      0  53.1000        S  False
4           0       3    male  35.000000      0      0   8.0500        S   True
..        ...     ...     ...        ...    ...    ...      ...      ...    ...
886         0       2    male  27.000000      0      0  13.0000        S   True
887         1       1  female  19.000000      0      0  30.0000        S   True
888         0       3  female  29.699118      1      2  23.4500        S  False
889         1       1    male  26.000000      0      0  30.0000        C   True
890         0       3    male  32.000000      0      0   7.7500        Q   True

[889 rows x 9 columns]

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
lb = LabelEncoder()

In [34]:
df.info()

<class 'pandas.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    int64
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    int64
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(6)
memory usage: 63.4 KB

In [33]:
df['sex'] = lb.fit_transform(df['sex'])
df['embarked'] = lb.fit_transform(df['embarked'])

In [35]:
df = df.astype('int')

In [36]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [37]:
x = df.drop(columns = 'survived')
y = df['survived']

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.2,random_state=42)

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
lr = LogisticRegression()

In [41]:
lr.fit(x_train,y_train)

LogisticRegression()

In [45]:
y_pred = lr.predict(x_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [46]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [47]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [48]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [49]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [51]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178