In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [36]:
df = sns.load_dataset('iris')

In [37]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [38]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
x = df.drop(columns='species')
y = df['species']

In [41]:
# cross validation we don't do train test split

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.33,random_state=42)

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
knn = KNeighborsClassifier(n_neighbors=5)
# if k = 15 accuracy is 1 
# knn = KNeighborsClassifier(n_neighbors=15)

In [54]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [55]:
knn.score(x_test,y_test)

0.98

In [69]:
from sklearn.svm import SVC
model_svm = SVC(C=30,kernel='linear',gamma='auto')
# model_svm = SVC(C=30,kernel='rbf',gamma='auto')

In [70]:
model_svm.fit(x_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [71]:
model_svm.score(x_test,y_test)

0.98

In [73]:
# how to use grid search cv
# cv -> cross validation 
# cv means jo data set hai lets say 100 % hai let say agar apan ne cv 5 raka to 
# uske 5 parts bnyega and har ek part se test krega bakio ko chod k

In [77]:
from sklearn.svm import SVC

In [78]:
model_svc = SVC(gamma='auto')

In [74]:
from sklearn.model_selection import GridSearchCV

In [83]:
classifier = GridSearchCV((model_svc),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [84]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [87]:
classifier.cv_results_

{'mean_fit_time': array([0.01051292, 0.00241451, 0.01120553, 0.00758195, 0.01115465,
        0.00435643, 0.00209961, 0.00240588]),
 'std_fit_time': array([0.01210322, 0.00060123, 0.01395916, 0.00543476, 0.01338551,
        0.00178826, 0.0002092 , 0.00079664]),
 'mean_score_time': array([0.00245147, 0.00139861, 0.00299792, 0.00779724, 0.00341187,
        0.00334697, 0.00180411, 0.00139375]),
 'std_score_time': array([0.00040465, 0.00049137, 0.00119542, 0.00911497, 0.00056722,
        0.00190839, 0.00040239, 0.00048201]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [88]:
results = pd.DataFrame(classifier.cv_results_)

In [89]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010513,0.012103,0.002451,0.000405,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002415,0.000601,0.001399,0.000491,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.011206,0.013959,0.002998,0.001195,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.007582,0.005435,0.007797,0.009115,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.011155,0.013386,0.003412,0.000567,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.004356,0.001788,0.003347,0.001908,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002100,0.000209,0.001804,0.000402,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002406,0.000797,0.001394,0.000482,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [91]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
# Data --> mode ---> cv -->grid

In [93]:
#random search cv

In [96]:
from sklearn.model_selection import RandomizedSearchCV

classifier_r = RandomizedSearchCV((model_svm),{
'C' : [1,10,20,30],
'kernel' : ['rof', 'linear'],
},n_iter = 10, cv = 5, return_train_score = False)

In [97]:
classifier_r.fit(x,y)

c:\Users\PIYUSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:326: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\PIYUSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
20 fits failed out of a total of 40.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\PIYUSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\PIYUSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
  File "c:\Users\PIYUSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\PIYUSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'kernel' parameter of SVC must be a str among {'linear', 'poly', 'sigmoid', 'precomputed', 'rbf'} or a callable. Got 'rof' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\PIYUSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan 0.98              nan 0.97333333        nan 0.96666667
        nan 0.96      ]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto', kernel='linear'),
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rof', 'linear']})

In [99]:
classifier_r.cv_results_

{'mean_fit_time': array([0.0050776 , 0.00334058, 0.0012012 , 0.00790606, 0.00081792,
        0.0023685 , 0.00080004, 0.00288634]),
 'std_fit_time': array([0.00790854, 0.00099463, 0.00116741, 0.00524127, 0.00041085,
        0.00058161, 0.00040002, 0.00084076]),
 'mean_score_time': array([0.        , 0.00251722, 0.        , 0.00399413, 0.        ,
        0.00153651, 0.        , 0.00160856]),
 'std_score_time': array([0.        , 0.00036725, 0.        , 0.00111402, 0.        ,
        0.00047167, 0.        , 0.00080855]),
 'param_kernel': masked_array(data=['rof', 'linear', 'rof', 'linear', 'rof', 'linear',
                    'rof', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rof', 'C': 1},
  {'kernel': 'linear', 'C': 1},
  {'kernel': 'rof', 'C': 10},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'rof', 'C': 20},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'rof', 'C': 30},
  {'kernel': 'linear', 'C': 30}],
 'split0_test_score': array([       nan, 0.96666667,        nan, 1.        ,        nan,
        1.        ,        nan, 1.        ]),
 'split1_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1.]),
 'split2_test_score': array([       nan, 0.96666667,        nan, 0.9       ,        nan,
        0.9       ,        nan, 0.9       ]),
 'split3_test_score': array([       nan, 0.96666667,        nan, 0.96666667,        nan,
        0.93333333,        nan, 0.9       ]),
 'split4_test_score': array([nan,  1., nan,  1., nan,  1., nan,  1.]),
 'mean_test_score': array([       nan, 0.98      ,        nan, 0.97333333,        nan,
        0.96666667,        nan, 0.96      ]),
 'std_test_score': array([       nan, 0.01632993,        nan, 0.03887301,        nan,
        0.0421637 ,        nan, 0.04898979]),
 'rank_test_score': array([5, 1, 5, 2, 5, 3, 5, 4], dtype=int32)}

In [101]:
result = pd.DataFrame(classifier_r.cv_results_)

In [102]:
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005078,0.007909,0.000000,0.000000,rof,1,"{'kernel': 'rof', 'C': 1}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,0.003341,0.000995,0.002517,0.000367,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.001201,0.001167,0.000000,0.000000,rof,10,"{'kernel': 'rof', 'C': 10}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.007906,0.005241,0.003994,0.001114,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
4,0.000818,0.000411,0.000000,0.000000,rof,20,"{'kernel': 'rof', 'C': 20}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.002368,0.000582,0.001537,0.000472,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3
6,0.000800,0.000400,0.000000,0.000000,rof,30,"{'kernel': 'rof', 'C': 30}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
7,0.002886,0.000841,0.001609,0.000809,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4

In [104]:
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rof              NaN
1        1       linear         0.980000
2       10          rof              NaN
3       10       linear         0.973333
4       20          rof              NaN
5       20       linear         0.966667
6       30          rof              NaN
7       30       linear         0.960000