In [4]:
# Introduction to Pandas
''' 
Pandas is open source library of python
which is used handle the data manipulation

'''

' \nPandas is open source library of python\nwhich is used handle the data manipulation\n\n'

In [5]:
# to install pandas -> !pip install pandas
# uv add pandas

In [6]:
# # Data structure of pandas:
# 1. series -> it return the values  not the columns name, it is one dimensional array
# 2. dataframe -> it return vaules as well as their columns/feature name

In [7]:
import pandas as pd
a = pd.Series([1,2,3,4])
print(type(a))
a

<class 'pandas.Series'>

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
# 2. Dataframe -> it is a multi-dimensional array and it reutrn  values  with column name
a = {
    'Emp_id':['A101','A102','A103','A104','A105'],
    'Emp_name':['John','Aman','sam','Rishi','Yuvraj'],
    'Emp_Det':['It',"operations",'sales','Hr','It'],
    'Salary':[10000,20000,12000,35000,38000],
    'Working_hours':[6,6,7,8,8]
}
b = pd.DataFrame(a)
print(b)

  Emp_id Emp_name     Emp_Det  Salary  Working_hours
0   A101     John          It   10000              6
1   A102     Aman  operations   20000              6
2   A103      sam       sales   12000              7
3   A104    Rishi          Hr   35000              8
4   A105   Yuvraj          It   38000              8

In [9]:
# how can we export our dataframe into the csv or any other file format
df = pd.DataFrame(a)
df

  Emp_id Emp_name     Emp_Det  Salary  Working_hours
0   A101     John          It   10000              6
1   A102     Aman  operations   20000              6
2   A103      sam       sales   12000              7
3   A104    Rishi          Hr   35000              8
4   A105   Yuvraj          It   38000              8

In [10]:
df.to_csv('emp_info.csv')

In [11]:
df.to_csv('new_Emp.csv',index = False)

In [12]:
# workin on covid data sets
df = pd.read_csv(r'C:\Users\PIYUSH\Downloads\Datasets\covid_toy - covid_toy.csv')
df.head()
# return top 5 data by default and if pass value in this it will return that rows from the dataset

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [13]:
# to check the bottom data
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [14]:
# to get the random rows from the dataset 
# by default it return only one row

df.sample(2)

    age  gender  fever cough     city has_covid
26   19  Female  100.0  Mild  Kolkata       Yes
54   60  Female   99.0  Mild   Mumbai       Yes

In [15]:
# how to check the data type of each row 
df.dtypes

age            int64
gender           str
fever        float64
cough            str
city             str
has_covid        str
dtype: object

In [16]:
# object are represented as categorical data

In [17]:
# how to check the statically view of the data frame
df.describe()
# What is df.describe()?

# df.describe() is a Pandas function that provides summary statistics for numerical
#  columns in a DataFrame. It helps us quickly understand the distribution and characteristics of the data.

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [18]:

# In this dataset, there are two numerical columns: age and fever.
# 1. Count
    # Number of non-missing values.
    # Age: 100 values are available.
    # Fever: Only 90 values are available, meaning 10 values are missing.
# 2. Mean (Average)
    # Sum of all values divided by the number of observations.
    # Average age = 44.22 years
    # Average fever = 100.84°F
# 3. Standard Deviation (Std)
    # Measures how spread out the values are from the mean.
    # Age std = 24.88 → Ages vary widely.
    # Fever std = 2.05 → Fever temperatures are relatively close to the average.
# 4. Minimum (Min)
    # Smallest value in the column.
    # Youngest age = 5 years
    # Lowest fever = 98°F
# 5. 25% (First Quartile, Q1)
    # 25% of observations are below this value.
    # 25% of people are 20 years or younger.
    # 25% of fever readings are 99°F or lower.
# 6. 50% (Median)
    # Middle value when data is sorted.
    # Median age = 45 years
    # Median fever = 101°F
# 7. 75% (Third Quartile, Q3)
    # 75% of observations are below this value.
    # 75% of people are 66.5 years or younger.
    # 75% of fever readings are 102.75°F or lower.
# 8. Maximum (Max)
    # Largest value in the column.
    # Oldest age = 84 years
    # Highest fever = 104°F

In [19]:
# how can we check overall information about the dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    str
 2   fever      90 non-null     float64
 3   cough      100 non-null    str
 4   city       100 non-null    str
 5   has_covid  100 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 4.8 KB

In [20]:
# how to check the missing values in  the dataframe
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [21]:
df['fever'].mean()

np.float64(100.84444444444445)

In [22]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [23]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [24]:
# how can we check total sub -categories  in a columns
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [25]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [26]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [27]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [28]:
df['city'] = df['city'].map({'Kolkata':0,'Bangalore':1,'Delhi':2,'Mumbai':3})
df['has_covid'] = df['has_covid'].map({'Yes':1,'No':0})
df['cough'] = df['cough'].map({'Mild':1,'Strong':0})
df['gender'] = df['gender'].map({'Male':0,'Female':1})

In [29]:

df

    age  gender  fever  cough  city  has_covid
0    60       0  103.0      1     0          0
1    27       0  100.0      1     2          1
2    42       0  101.0      1     2          0
3    31       1   98.0      1     0          0
4    65       1  101.0      1     3          0
..  ...     ...    ...    ...   ...        ...
95   12       1  104.0      1     1          0
96   51       1  101.0      0     0          1
97   20       1  101.0      1     1          0
98    5       1   98.0      0     3          0
99   10       1   98.0      0     0          1

[100 rows x 6 columns]

In [30]:
# loc() and iloc()
# loc -> df.loc[row_range,columns_name] ---> start value  include and last value include
# iloc->df.iloc[row_range,columns_range] --->start value include but last value exclude

df.loc[5:10,['gender','cough','age']]

    gender  cough  age
5        1      1   84
6        0      0   14
7        1      0   20
8        1      0   19
9        1      1   64
10       1      1   75

In [31]:
df.iloc[5:10,[0,2,3]]

   age       fever  cough
5   84  100.844444      1
6   14  101.000000      0
7   20  100.844444      0
8   19  100.000000      0
9   64  101.000000      1

In [32]:
df.iloc[5:10,[0,2]] = 55

In [33]:
# 
df.head(10)

   age  gender  fever  cough  city  has_covid
0   60       0  103.0      1     0          0
1   27       0  100.0      1     2          1
2   42       0  101.0      1     2          0
3   31       1   98.0      1     0          0
4   65       1  101.0      1     3          0
5   55       1   55.0      1     1          1
6   55       0   55.0      0     1          0
7   55       1   55.0      0     3          1
8   55       1   55.0      0     1          0
9   55       1   55.0      1     2          0

In [34]:
# how to delete the columns from the datafram we just deleted from the copy not from the original
df.drop(columns=['age'])

    gender  fever  cough  city  has_covid
0        0  103.0      1     0          0
1        0  100.0      1     2          1
2        0  101.0      1     2          0
3        1   98.0      1     0          0
4        1  101.0      1     3          0
..     ...    ...    ...   ...        ...
95       1  104.0      1     1          0
96       1  101.0      0     0          1
97       1  101.0      1     1          0
98       1   98.0      0     3          0
99       1   98.0      0     0          1

[100 rows x 5 columns]

In [35]:
df

    age  gender  fever  cough  city  has_covid
0    60       0  103.0      1     0          0
1    27       0  100.0      1     2          1
2    42       0  101.0      1     2          0
3    31       1   98.0      1     0          0
4    65       1  101.0      1     3          0
..  ...     ...    ...    ...   ...        ...
95   12       1  104.0      1     1          0
96   51       1  101.0      0     0          1
97   20       1  101.0      1     1          0
98    5       1   98.0      0     3          0
99   10       1   98.0      0     0          1

[100 rows x 6 columns]

In [36]:
df = df.drop(columns = ['city'])

In [37]:
df

    age  gender  fever  cough  has_covid
0    60       0  103.0      1          0
1    27       0  100.0      1          1
2    42       0  101.0      1          0
3    31       1   98.0      1          0
4    65       1  101.0      1          0
..  ...     ...    ...    ...        ...
95   12       1  104.0      1          0
96   51       1  101.0      0          1
97   20       1  101.0      1          0
98    5       1   98.0      0          0
99   10       1   98.0      0          1

[100 rows x 5 columns]

In [38]:
df.sort_index(axis = 0)  # sort the data

    age  gender  fever  cough  has_covid
0    60       0  103.0      1          0
1    27       0  100.0      1          1
2    42       0  101.0      1          0
3    31       1   98.0      1          0
4    65       1  101.0      1          0
..  ...     ...    ...    ...        ...
95   12       1  104.0      1          0
96   51       1  101.0      0          1
97   20       1  101.0      1          0
98    5       1   98.0      0          0
99   10       1   98.0      0          1

[100 rows x 5 columns]

In [39]:
df.sort_index(axis = 1)  # sort the data

    age  cough  fever  gender  has_covid
0    60      1  103.0       0          0
1    27      1  100.0       0          1
2    42      1  101.0       0          0
3    31      1   98.0       1          0
4    65      1  101.0       1          0
..  ...    ...    ...     ...        ...
95   12      1  104.0       1          0
96   51      0  101.0       1          1
97   20      1  101.0       1          0
98    5      0   98.0       1          0
99   10      0   98.0       1          1

[100 rows x 5 columns]

In [40]:
df = df.rename(columns={'cough':'updated_cough'})

In [41]:
df

    age  gender  fever  updated_cough  has_covid
0    60       0  103.0              1          0
1    27       0  100.0              1          1
2    42       0  101.0              1          0
3    31       1   98.0              1          0
4    65       1  101.0              1          0
..  ...     ...    ...            ...        ...
95   12       1  104.0              1          0
96   51       1  101.0              0          1
97   20       1  101.0              1          0
98    5       1   98.0              0          0
99   10       1   98.0              0          1

[100 rows x 5 columns]

In [42]:
# columns name and subcatergoris are the name sensitive small mistake will make new colm
df['Age'] = df['age'].add(20)

In [43]:
df

    age  gender  fever  updated_cough  has_covid  Age
0    60       0  103.0              1          0   80
1    27       0  100.0              1          1   47
2    42       0  101.0              1          0   62
3    31       1   98.0              1          0   51
4    65       1  101.0              1          0   85
..  ...     ...    ...            ...        ...  ...
95   12       1  104.0              1          0   32
96   51       1  101.0              0          1   71
97   20       1  101.0              1          0   40
98    5       1   98.0              0          0   25
99   10       1   98.0              0          1   30

[100 rows x 6 columns]

In [44]:
df['fever'] = df['fever'].sub(100)
df

    age  gender  fever  updated_cough  has_covid  Age
0    60       0    3.0              1          0   80
1    27       0    0.0              1          1   47
2    42       0    1.0              1          0   62
3    31       1   -2.0              1          0   51
4    65       1    1.0              1          0   85
..  ...     ...    ...            ...        ...  ...
95   12       1    4.0              1          0   32
96   51       1    1.0              0          1   71
97   20       1    1.0              1          0   40
98    5       1   -2.0              0          0   25
99   10       1   -2.0              0          1   30

[100 rows x 6 columns]

In [45]:
df[['age','fever']] # using this we can fileter the data

    age  fever
0    60    3.0
1    27    0.0
2    42    1.0
3    31   -2.0
4    65    1.0
..  ...    ...
95   12    4.0
96   51    1.0
97   20    1.0
98    5   -2.0
99   10   -2.0

[100 rows x 2 columns]

In [46]:
# in pandas axix = 0  means row wise and axis  = 1 means col wise

In [ ]:
df.groupby('gender').size()

gender
0    41
1    59
dtype: int64