In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r'C:\Users\PIYUSH\Downloads\Datasets\placement - placement.csv')

In [6]:
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [7]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [8]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [9]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [10]:
df.sample()

    cgpa  resume_score  placed
63  8.65          7.58       1

In [16]:
df.iloc[0:4,[0,1,2]]

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [18]:
df.loc[0:4,['cgpa','resume_score','placed']]

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [19]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [21]:
df.describe()

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [23]:
s = df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='str')]

In [24]:
p = df.dtypes
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [ ]:
b = df.empty # it return true if ther is any missing value in the dataset
b

False

In [28]:
df = df.dropna() # for check missing value

In [ ]:
df.ndim # number of axex

2

In [30]:
df.shape

(100, 3)

In [31]:
df.shape[0] # give the total number of rows in the data
df.shape[1]# give the total number of columns in the dataset

3

In [ ]:
df.size  # row count * col_Count

300

In [ ]:
df.values # get a numpy array for df values

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [34]:
df = df.copy()

In [37]:
p = df.sort_values(by = 'resume_score')
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [39]:
# x =  df.astype(int) # type conversion
df['cgpa'] = df['cgpa'].astype(int)
df

    cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [42]:
df['cgpa'] = df['cgpa'].astype(str)
df

   cgpa  resume_score  placed
0     8          6.52       1
1     6          5.17       0
2     8          8.86       1
3     6          7.27       1
4     7          7.30       1
..  ...           ...     ...
95    6          6.38       0
96    8          7.76       1
97    6          7.78       0
98    8          5.63       1
99    6          6.61       0

[100 rows x 3 columns]

In [43]:
df.dtypes

cgpa                str
resume_score    float64
placed            int64
dtype: object

In [45]:
df['cgpa'] = df['cgpa'].astype(int)
df

    cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [46]:
df['cgpa'] = df['cgpa'].add(4)

In [47]:
s = df.count()
s

cgpa            100
resume_score    100
placed          100
dtype: int64

In [48]:
df.max()

cgpa            13.00
resume_score     9.06
placed           1.00
dtype: float64

In [49]:
df.min()

cgpa            9.00
resume_score    4.95
placed          0.00
dtype: float64

In [50]:
g = df.filter(items = ['cgpa','placed'])
g

    cgpa  placed
0     12       1
1     10       0
2     12       1
3     10       1
4     11       1
..   ...     ...
95    10       0
96    12       1
97    10       0
98    12       1
99    10       0

[100 rows x 2 columns]

In [51]:
df[['cgpa','placed']]

    cgpa  placed
0     12       1
1     10       0
2     12       1
3     10       1
4     11       1
..   ...     ...
95    10       0
96    12       1
97    10       0
98    12       1
99    10       0

[100 rows x 2 columns]

In [55]:
df.filter(items = [5,6] ,axis = 0)  # axis  = 0 menas row wise operation

   cgpa  resume_score  placed
5    12          6.19       1
6     9          7.09       0

In [56]:
df.filter(like = '5', axis = 0)

    cgpa  resume_score  placed
5     12          6.19       1
15    12          5.93       1
25    11          5.68       1
35    12          7.48       1
45    12          5.44       1
50    12          6.74       1
51    10          7.39       0
52     9          7.50       0
53    10          7.16       0
54     9          7.18       0
55    10          6.87       1
56    10          6.43       0
57    10          7.21       0
58    10          7.37       0
59     9          7.57       0
65    10          8.75       0
75    10          7.94       1
85    10          5.46       0
95    10          6.38       0

In [58]:
s = df.to_dict()
s

{'cgpa': {0: 12,
  1: 10,
  2: 12,
  3: 10,
  4: 11,
  5: 12,
  6: 9,
  7: 10,
  8: 10,
  9: 11,
  10: 10,
  11: 9,
  12: 10,
  13: 12,
  14: 11,
  15: 12,
  16: 12,
  17: 11,
  18: 9,
  19: 10,
  20: 9,
  21: 10,
  22: 10,
  23: 10,
  24: 12,
  25: 11,
  26: 10,
  27: 9,
  28: 11,
  29: 10,
  30: 11,
  31: 9,
  32: 9,
  33: 12,
  34: 12,
  35: 12,
  36: 12,
  37: 13,
  38: 10,
  39: 11,
  40: 12,
  41: 12,
  42: 10,
  43: 12,
  44: 9,
  45: 12,
  46: 9,
  47: 11,
  48: 9,
  49: 9,
  50: 12,
  51: 10,
  52: 9,
  53: 10,
  54: 9,
  55: 10,
  56: 10,
  57: 10,
  58: 10,
  59: 9,
  60: 9,
  61: 10,
  62: 9,
  63: 12,
  64: 11,
  65: 10,
  66: 12,
  67: 10,
  68: 10,
  69: 12,
  70: 11,
  71: 11,
  72: 11,
  73: 9,
  74: 9,
  75: 10,
  76: 13,
  77: 9,
  78: 9,
  79: 9,
  80: 11,
  81: 10,
  82: 11,
  83: 11,
  84: 9,
  85: 10,
  86: 10,
  87: 9,
  88: 12,
  89: 9,
  90: 9,
  91: 12,
  92: 9,
  93: 13,
  94: 12,
  95: 10,
  96: 12,
  97: 10,
  98: 12,
  99: 10},
 'resume_score': {0: 6.52,
  1: 5.17,
  2: 8.86,
  3: 7.27,
  4: 7.3,
  5: 6.19,
  6: 7.09,
  7: 6.29,
  8: 6.71,
  9: 7.12,
  10: 6.35,
  11: 6.54,
  12: 7.01,
  13: 5.09,
  14: 6.25,
  15: 5.93,
  16: 7.64,
  17: 8.71,
  18: 5.88,
  19: 8.11,
  20: 8.06,
  21: 7.64,
  22: 5.77,
  23: 7.13,
  24: 6.18,
  25: 5.68,
  26: 6.47,
  27: 6.15,
  28: 7.67,
  29: 7.3,
  30: 7.15,
  31: 7.02,
  32: 7.96,
  33: 7.73,
  34: 7.19,
  35: 7.48,
  36: 7.56,
  37: 8.21,
  38: 8.72,
  39: 6.19,
  40: 5.32,
  41: 5.15,
  42: 6.91,
  43: 7.95,
  44: 5.92,
  45: 5.44,
  46: 5.21,
  47: 8.14,
  48: 6.57,
  49: 6.73,
  50: 6.74,
  51: 7.39,
  52: 7.5,
  53: 7.16,
  54: 7.18,
  55: 6.87,
  56: 6.43,
  57: 7.21,
  58: 7.37,
  59: 7.57,
  60: 6.64,
  61: 7.96,
  62: 8.43,
  63: 7.58,
  64: 8.09,
  65: 8.75,
  66: 8.02,
  67: 6.81,
  68: 7.49,
  69: 9.06,
  70: 7.41,
  71: 8.22,
  72: 7.98,
  73: 6.48,
  74: 7.36,
  75: 7.94,
  76: 5.5,
  77: 6.92,
  78: 5.66,
  79: 7.28,
  80: 7.7,
  81: 6.72,
  82: 6.06,
  83: 8.08,
  84: 6.49,
  85: 5.46,
  86: 5.76,
  87: 5.05,
  88: 6.07,
  89: 7.49,
  90: 5.56,
  91: 6.3,
  92: 6.18,
  93: 7.39,
  94: 4.95,
  95: 6.38,
  96: 7.76,
  97: 7.78,
  98: 5.63,
  99: 6.61},
 'placed': {0: 1,
  1: 0,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 0,
  7: 0,
  8: 0,
  9: 1,
  10: 0,
  11: 0,
  12: 0,
  13: 1,
  14: 1,
  15: 1,
  16: 1,
  17: 1,
  18: 0,
  19: 1,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 1,
  25: 1,
  26: 0,
  27: 0,
  28: 1,
  29: 0,
  30: 1,
  31: 0,
  32: 0,
  33: 1,
  34: 1,
  35: 1,
  36: 1,
  37: 1,
  38: 0,
  39: 1,
  40: 1,
  41: 1,
  42: 1,
  43: 1,
  44: 0,
  45: 1,
  46: 0,
  47: 1,
  48: 0,
  49: 0,
  50: 1,
  51: 0,
  52: 0,
  53: 0,
  54: 0,
  55: 1,
  56: 0,
  57: 0,
  58: 0,
  59: 0,
  60: 0,
  61: 1,
  62: 0,
  63: 1,
  64: 1,
  65: 0,
  66: 1,
  67: 1,
  68: 0,
  69: 1,
  70: 1,
  71: 1,
  72: 1,
  73: 0,
  74: 0,
  75: 1,
  76: 1,
  77: 0,
  78: 0,
  79: 0,
  80: 1,
  81: 0,
  82: 1,
  83: 1,
  84: 0,
  85: 0,
  86: 0,
  87: 0,
  88: 1,
  89: 0,
  90: 0,
  91: 1,
  92: 0,
  93: 1,
  94: 1,
  95: 0,
  96: 1,
  97: 0,
  98: 1,
  99: 0}}

In [59]:
df['half'] = df['cgpa'].where(df['cgpa'] > 7, other = 0)
df.head()

   cgpa  resume_score  placed  half
0    12          6.52       1    12
1    10          5.17       0    10
2    12          8.86       1    12
3    10          7.27       1    10
4    11          7.30       1    11